== OGC API Collections for Aviation Meteorology Messages

Paragraph

=== Requirement Class Aviation Meteorology Message Collections - Core

Paragraph – intro text for the requirement class.

Use the following table for Requirements Classes.

include::../requirements/requirements_class_avimet_collections_core.adoc[]

==== Requirement 1

Paragraph - intro text for the requirement.

Use the following table for Requirements, number sequentially.

include::../requirements/requirement001.adoc[]

Dictionary tables for requirements can be added as necessary. Modify the following example as needed.

[width="90%",options="header"]
|===
|Names |Definition |Data types and values |Multiplicity and use
|name 1 |definition of name 1 |float |One or more (mandatory)
|name 2 |definition of name 2 |character string type, not empty |Zero or one (optional)
|name 3 |definition of name 3 |GML:: Point PropertyType |One (mandatory)
|===


==== Requirement 2

Paragraph - intro text for the requirement.

Use the following table for Requirements, number sequentially.

include::../requirements/requirement002.adoc[]


=== Requirement Class METAR Collection

Paragraph – intro text for the requirement class.

Use the following table for Requirements Classes.

include::../requirements/requirements_class_METAR_collection.adoc[]


=== Requirement Class TAF Collection

Paragraph – intro text for the requirement class.

Use the following table for Requirements Classes.

include::../requirements/requirements_class_TAF_collection.adoc[]


=== Requirement Class SIGMET Collection

Paragraph – intro text for the requirement class.

Use the following table for Requirements Classes.

include::../requirements/requirements_class_SIGMET_collection.adoc[]

